# Generated by Django 3.1.1 on 2020-09-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200910_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_downloadable',
        ),
    ]
